"""Pure calculations for the Energy page's read-first summary.

The rendering layer uses these helpers so the top-level diagnosis and the
supporting chapters share the same calculations.  No prose is generated by an
external model: identical data always produce identical output.
"""

from __future__ import annotations

import numpy as np
import pandas as pd


def _frame(value) -> pd.DataFrame:
    return value.copy() if isinstance(value, pd.DataFrame) else pd.DataFrame()


def _numeric(value) -> float:
    number = pd.to_numeric(value, errors="coerce")
    return float(number) if pd.notna(number) and np.isfinite(number) else np.nan


def rolling_value(retail: pd.DataFrame, sector: str, *, months: int = 12, offset: int = 0) -> float:
    clean = _frame(retail)
    if clean.empty or not {"Date", "Geography", "Sector", "Sales MWh"}.issubset(clean.columns):
        return np.nan
    clean["Date"] = pd.to_datetime(clean["Date"], errors="coerce", format="mixed")
    clean["Sales MWh"] = pd.to_numeric(clean["Sales MWh"], errors="coerce")
    clean = clean.loc[
        clean["Geography"].fillna("").astype(str).eq("United States")
        & clean["Sector"].fillna("").astype(str).eq(sector)
    ].dropna(subset=["Date", "Sales MWh"])
    if clean.empty:
        return np.nan
    latest = clean["Date"].max() - pd.DateOffset(months=offset)
    lower = latest - pd.DateOffset(months=months)
    return float(clean.loc[(clean["Date"] <= latest) & (clean["Date"] > lower), "Sales MWh"].sum())


def rolling_growth(retail: pd.DataFrame, sector: str) -> float:
    current = rolling_value(retail, sector, months=12, offset=0)
    previous = rolling_value(retail, sector, months=12, offset=12)
    if pd.isna(current) or pd.isna(previous) or previous <= 0:
        return np.nan
    return float((current / previous - 1.0) * 100.0)


def latest_retail_value(retail: pd.DataFrame, sector: str, field: str) -> float:
    clean = _frame(retail)
    if clean.empty or not {"Date", "Geography", "Sector", field}.issubset(clean.columns):
        return np.nan
    clean["Date"] = pd.to_datetime(clean["Date"], errors="coerce", format="mixed")
    clean[field] = pd.to_numeric(clean[field], errors="coerce")
    clean = clean.loc[
        clean["Geography"].fillna("").astype(str).eq("United States")
        & clean["Sector"].fillna("").astype(str).eq(sector)
    ].dropna(subset=["Date", field])
    return np.nan if clean.empty else float(clean.sort_values("Date", kind="stable").iloc[-1][field])


def latest_retail_growth(retail: pd.DataFrame, sector: str, field: str) -> float:
    clean = _frame(retail)
    if clean.empty or not {"Date", "Geography", "Sector", field}.issubset(clean.columns):
        return np.nan
    clean["Date"] = pd.to_datetime(clean["Date"], errors="coerce", format="mixed")
    clean[field] = pd.to_numeric(clean[field], errors="coerce")
    clean = clean.loc[
        clean["Geography"].fillna("").astype(str).eq("United States")
        & clean["Sector"].fillna("").astype(str).eq(sector)
    ].dropna(subset=["Date", field]).sort_values("Date", kind="stable")
    if clean.empty:
        return np.nan
    latest = clean.iloc[-1]
    target = latest["Date"] - pd.DateOffset(months=12)
    prior = clean.loc[clean["Date"] <= target]
    if prior.empty:
        return np.nan
    previous = float(prior.iloc[-1][field])
    current = float(latest[field])
    return float((current / previous - 1.0) * 100.0) if previous > 0 else np.nan


def demand_snapshot(retail: pd.DataFrame) -> dict:
    return {
        "total_twh": rolling_value(retail, "Total") / 1_000_000.0,
        "total_growth": rolling_growth(retail, "Total"),
        "commercial_growth": rolling_growth(retail, "Commercial"),
        "industrial_growth": rolling_growth(retail, "Industrial"),
        "customers_m": latest_retail_value(retail, "Total", "Customers") / 1_000_000.0,
    }


def large_load_snapshot(campuses: pd.DataFrame) -> dict:
    clean = _frame(campuses)
    if clean.empty:
        return {
            "active_campuses": 0,
            "operating_campuses": 0,
            "development_campuses": 0,
            "published_records": 0,
            "published_coverage": np.nan,
            "published_total_mw": np.nan,
            "published_median_mw": np.nan,
            "published_mean_mw": np.nan,
        }
    status = clean.get("Status", pd.Series("", index=clean.index)).fillna("").astype(str)
    published = pd.to_numeric(
        clean.get("Published Capacity Estimate MW", pd.Series(np.nan, index=clean.index)),
        errors="coerce",
    ).where(lambda values: values > 0)
    active_count = int(len(clean))
    published_count = int(published.notna().sum())
    development_statuses = {
        "Announced", "Proposed", "Planned", "Under construction",
        "Approved / permitted / under construction", "Expanding",
    }
    return {
        "active_campuses": active_count,
        "operating_campuses": int(status.eq("Operational").sum()),
        "development_campuses": int(status.isin(development_statuses).sum()),
        "published_records": published_count,
        "published_coverage": published_count / active_count if active_count else np.nan,
        "published_total_mw": published.sum(min_count=1),
        "published_median_mw": published.median(),
        "published_mean_mw": published.mean(),
    }


def generation_snapshot(generation: pd.DataFrame) -> dict:
    clean = _frame(generation)
    required = {"Date", "Period Type", "Source", "Generation GWh"}
    if clean.empty or not required.issubset(clean.columns):
        return {"total_twh": np.nan, "gas_share": np.nan, "nuclear_share": np.nan, "renewable_share": np.nan}
    clean["Date"] = pd.to_datetime(clean["Date"], errors="coerce", format="mixed")
    clean["Generation GWh"] = pd.to_numeric(clean["Generation GWh"], errors="coerce")
    clean = clean.loc[clean["Period Type"].fillna("").astype(str).eq("Monthly")].dropna(
        subset=["Date", "Generation GWh"]
    )
    if clean.empty:
        return {"total_twh": np.nan, "gas_share": np.nan, "nuclear_share": np.nan, "renewable_share": np.nan}
    latest = clean["Date"].max()
    window = clean.loc[clean["Date"] > latest - pd.DateOffset(months=12)]
    by_source = window.groupby("Source")["Generation GWh"].sum()
    total = float(by_source.sum())
    renewables = float(by_source.reindex(["Hydro", "Solar", "Wind + other renewables"]).fillna(0).sum())
    return {
        "total_twh": total / 1000.0,
        "gas_share": float(by_source.get("Natural gas", 0.0) / total * 100.0) if total else np.nan,
        "nuclear_share": float(by_source.get("Nuclear", 0.0) / total * 100.0) if total else np.nan,
        "renewable_share": renewables / total * 100.0 if total else np.nan,
    }


def supply_snapshot(generation: pd.DataFrame, capacity: pd.DataFrame, changes: pd.DataFrame) -> dict:
    snapshot = generation_snapshot(generation)
    capacity_clean = _frame(capacity)
    changes_clean = _frame(changes)
    capacity_values = pd.to_numeric(
        capacity_clean.get("Net Summer Capacity MW", pd.Series(dtype=float)), errors="coerce"
    )
    storage_values = pd.to_numeric(
        capacity_clean.get("Storage Energy MWh", pd.Series(dtype=float)), errors="coerce"
    )
    technology = capacity_clean.get("Technology Group", pd.Series("", index=capacity_clean.index)).fillna("").astype(str)
    change_values = pd.to_numeric(
        changes_clean.get("Net Summer Capacity (MW)", pd.Series(dtype=float)), errors="coerce"
    )
    change_type = changes_clean.get("Pipeline Type", pd.Series("", index=changes_clean.index)).fillna("").astype(str)
    snapshot.update({
        "capacity_gw": capacity_values.sum(min_count=1) / 1000.0,
        "battery_gw": capacity_values.loc[technology.eq("Battery storage")].sum(min_count=1) / 1000.0,
        "storage_gwh": storage_values.sum(min_count=1) / 1000.0,
        "current_additions_gw": change_values.loc[change_type.eq("Addition")].sum(min_count=1) / 1000.0,
        "current_retirements_gw": change_values.loc[change_type.eq("Retirement")].sum(min_count=1) / 1000.0,
    })
    return snapshot


def development_snapshot(
    pipeline: pd.DataFrame,
    queue: pd.DataFrame,
    queue_summary: pd.DataFrame,
    *,
    current_year: int | None = None,
    end_year: int = 2030,
) -> dict:
    year = int(current_year or pd.Timestamp.now().year)
    pipeline_clean = _frame(pipeline)
    pipeline_clean["Expected Year"] = pd.to_numeric(
        pipeline_clean.get("Expected Year", pd.Series(np.nan, index=pipeline_clean.index)), errors="coerce"
    )
    pipeline_clean["Nameplate Capacity (MW)"] = pd.to_numeric(
        pipeline_clean.get("Nameplate Capacity (MW)", pd.Series(np.nan, index=pipeline_clean.index)), errors="coerce"
    )
    near = pipeline_clean.loc[pipeline_clean["Expected Year"].between(year, end_year)].copy()
    pipeline_type = near.get("Pipeline Type", pd.Series("", index=near.index)).fillna("").astype(str)
    additions = near.loc[pipeline_type.eq("Addition"), "Nameplate Capacity (MW)"].sum(min_count=1) / 1000.0
    retirements = near.loc[pipeline_type.eq("Retirement"), "Nameplate Capacity (MW)"].sum(min_count=1) / 1000.0

    queue_clean = _frame(queue)
    if "q_status" in queue_clean.columns:
        queue_clean = queue_clean.loc[queue_clean["q_status"].fillna("").astype(str).eq("active")].copy()
    else:
        queue_clean = pd.DataFrame()
    queue_clean["Queue MW"] = pd.to_numeric(
        queue_clean.get("Queue MW", pd.Series(np.nan, index=queue_clean.index)), errors="coerce"
    )
    submitted_queue_gw = queue_clean["Queue MW"].sum(min_count=1) / 1000.0

    summary_clean = _frame(queue_summary)
    summary_available = (
        {"Technology Group", "Queue GW"}.issubset(summary_clean.columns)
        and pd.to_numeric(summary_clean["Queue GW"], errors="coerce").notna().any()
    )
    if summary_available:
        summary_clean["Queue GW"] = pd.to_numeric(summary_clean["Queue GW"], errors="coerce")
        headline_queue_gw = summary_clean["Queue GW"].sum(min_count=1)
        technology_frame = summary_clean
        technology_note = "Berkeley Lab component accounting"
        queue_context = f"{len(queue_clean):,} projects · component accounting"
    else:
        headline_queue_gw = submitted_queue_gw
        technology_frame = queue_clean
        technology_note = "Submitted components; summary unavailable"
        queue_context = f"{len(queue_clean):,} projects · submitted components"

    if "IA_phase_clean" in queue_clean.columns:
        advanced_gw = queue_clean.loc[
            queue_clean["IA_phase_clean"].isin(["IA Executed", "Construction"]), "Queue MW"
        ].sum(min_count=1) / 1000.0
    else:
        advanced_gw = np.nan
    advanced_share = advanced_gw / submitted_queue_gw * 100.0 if pd.notna(advanced_gw) and submitted_queue_gw > 0 else np.nan

    additions_by_technology = pd.DataFrame()
    if {"Technology Group", "Pipeline Type", "Nameplate Capacity (MW)"}.issubset(near.columns):
        additions_by_technology = (
            near.loc[pipeline_type.eq("Addition")]
            .groupby("Technology Group", as_index=False)["Nameplate Capacity (MW)"]
            .sum()
            .sort_values("Nameplate Capacity (MW)", ascending=False, kind="stable")
        )
    leading_technologies = additions_by_technology.head(2).get("Technology Group", pd.Series(dtype=str)).astype(str).tolist()

    return {
        "current_year": year,
        "end_year": int(end_year),
        "planned_additions_gw": float(additions) if pd.notna(additions) else np.nan,
        "planned_retirements_gw": float(retirements) if pd.notna(retirements) else np.nan,
        "planned_net_gw": float(additions - retirements) if pd.notna(additions) and pd.notna(retirements) else np.nan,
        "headline_queue_gw": float(headline_queue_gw) if pd.notna(headline_queue_gw) else np.nan,
        "submitted_queue_gw": float(submitted_queue_gw) if pd.notna(submitted_queue_gw) else np.nan,
        "advanced_gw": float(advanced_gw) if pd.notna(advanced_gw) else np.nan,
        "advanced_share": float(advanced_share) if pd.notna(advanced_share) else np.nan,
        "queue_projects": int(len(queue_clean)),
        "queue_context": queue_context,
        "technology_note": technology_note,
        "technology_frame": technology_frame,
        "active_queue": queue_clean,
        "pipeline": pipeline_clean,
        "leading_technologies": leading_technologies,
    }


def price_snapshot(retail: pd.DataFrame, gas_item: dict | None = None) -> dict:
    gas = gas_item or {}
    return {
        "residential": latest_retail_value(retail, "Residential", "Price Cents per kWh"),
        "commercial": latest_retail_value(retail, "Commercial", "Price Cents per kWh"),
        "industrial": latest_retail_value(retail, "Industrial", "Price Cents per kWh"),
        "total": latest_retail_value(retail, "Total", "Price Cents per kWh"),
        "total_growth": latest_retail_growth(retail, "Total", "Price Cents per kWh"),
        "gas_value": _numeric(gas.get("value")),
        "gas_date": gas.get("date"),
    }


def _fmt(value: float, digits: int = 1, *, signed: bool = False) -> str:
    if pd.isna(value) or not np.isfinite(value):
        return "n/a"
    spec = f"+,.{digits}f" if signed else f",.{digits}f"
    return format(float(value), spec)
