"""Adversarial contract for general editorial quality, not phrase matching."""

from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from analytics.editorial_quality import assess_read_quality, compare_macro_reads  # noqa: E402
from analytics.read_models import GeneratedMacroParagraph, GeneratedMacroRead, SupportedSentence  # noqa: E402


def sentence(text: str, *fact_ids: str) -> SupportedSentence:
    return SupportedSentence(text=text, fact_ids=list(fact_ids), inference="interpretation")


def macro(first_sentence: str) -> GeneratedMacroRead:
    return GeneratedMacroRead(
        selected_domains=["finance", "data_center", "grid_storage", "adoption", "economic_impact"],
        headline=sentence(
            "Investment has moved ahead of infrastructure use and broad economic gains.",
            "finance.forward", "data_center.pipeline", "adoption.use", "economic_impact.productivity",
        ),
        paragraphs=[
            GeneratedMacroParagraph(sentences=[
                sentence(first_sentence, "finance.coverage", "finance.forward"),
                sentence("Investors continue to support projects that can expand the country's computing base.", "finance.forward", "data_center.pipeline"),
                sentence("That support begins the process, but operating facilities determine how much capacity becomes useful.", "finance.forward", "data_center.pipeline"),
            ]),
            GeneratedMacroParagraph(sentences=[
                sentence("Grid access limits how quickly planned data centers can begin operating.", "data_center.pipeline", "grid_storage.queue"),
                sentence("Utilities must connect each facility before servers can provide computing services.", "data_center.pipeline", "grid_storage.queue"),
                sentence("This physical work separates an announced project from capacity that businesses can use.", "data_center.pipeline", "adoption.use"),
            ]),
            GeneratedMacroParagraph(sentences=[
                sentence("Business use remains too narrow to connect available capacity with economy-wide gains.", "adoption.use", "economic_impact.productivity"),
                sentence("Regular adoption would allow more firms to turn computing services into changes in daily production.", "adoption.use", "economic_impact.productivity"),
                sentence("The evidence therefore supports an expanding buildout without yet establishing a broad economic payoff.", "finance.forward", "economic_impact.productivity"),
            ]),
        ],
    )


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def main() -> None:
    production_failure = macro(
        "Operating cash covers current capital spending at covered companies, but the 5.04-times commitment load pushes funding needs well beyond today's build."
    )
    production_score = assess_read_quality(production_failure, scope="macro")
    require(not production_score.passed, "The exact production failure passed the editorial gate.")
    require(any(issue.reason == "historical_failure_reuse" for issue in production_score.issues), "Historical production failure was not identified.")

    # Holdout wording is intentionally absent from editorial_regression_cases.json.
    # Passing this test requires structural detection, not an exact blacklist hit.
    unseen_paraphrase = macro(
        "Cash generated by covered firms pays for present capex, although commitments at 5.04 times spending carry financing requirements beyond the construction now under way."
    )
    paraphrase_score = assess_read_quality(unseen_paraphrase, scope="macro")
    require(not paraphrase_score.passed, "An unseen overloaded paraphrase passed the editorial gate.")
    require(
        any(issue.reason in {"abstract_noun_stack", "overloaded_time_contrast", "spoken_length"} for issue in paraphrase_score.issues),
        "Unseen paraphrase was rejected only by phrase matching rather than structural analysis.",
    )

    revised = macro("These companies generate enough cash to fund their current capital spending.")
    revised_score = assess_read_quality(revised, scope="macro")
    require(revised_score.passed, f"Concrete revision failed the editorial gate: {revised_score.to_dict()}")
    comparison = compare_macro_reads(production_failure, revised)
    require(comparison["passed"], f"Materially improved revision failed comparative gating: {comparison}")

    print(
        "PASS editorial quality contract · exact failure rejected · unseen structural paraphrase rejected · "
        f"revision improved {comparison['macro']['actual_improvement']} points"
    )


if __name__ == "__main__":
    main()
