"""Canonical market-universe configuration.

The v5.17 universe contains 204 companies across 15 exclusive sectors.
Ticker ownership is exclusive: a symbol may occur in exactly one basket.
"""

UNIVERSE_VERSION = '204x15-v1'
EXPECTED_SECTOR_COUNT = 15
EXPECTED_TICKER_COUNT = 204

SECTOR_CONFIG = {'COMPUTE': {'basket': ['NVDA',
                        'AMD',
                        'AVGO',
                        'MRVL',
                        'ARM',
                        'QCOM',
                        'MU',
                        'TSM',
                        'INTC',
                        'CRDO',
                        'ADI',
                        'NXPI',
                        'ON',
                        'MCHP',
                        'MPWR',
                        'LSCC',
                        'ALAB',
                        'GFS'],
             'ai_exposure_score': {'NVDA': 5,
                                   'AMD': 5,
                                   'AVGO': 5,
                                   'MRVL': 4,
                                   'ARM': 4,
                                   'QCOM': 3,
                                   'MU': 4,
                                   'TSM': 4,
                                   'INTC': 3,
                                   'CRDO': 5,
                                   'ADI': 2,
                                   'NXPI': 2,
                                   'ON': 2,
                                   'MCHP': 2,
                                   'MPWR': 3,
                                   'LSCC': 3,
                                   'ALAB': 4,
                                   'GFS': 3}},
 'SEMICAP_EQUIPMENT': {'basket': ['ASML',
                                  'AMAT',
                                  'LRCX',
                                  'KLAC',
                                  'TER',
                                  'ONTO',
                                  'ACLS',
                                  'AEIS',
                                  'MKSI',
                                  'ICHR',
                                  'UCTT',
                                  'FORM',
                                  'CAMT',
                                  'KLIC',
                                  'ENTG',
                                  'AMKR',
                                  'CDNS',
                                  'SNPS'],
                       'ai_exposure_score': {'ASML': 5,
                                             'AMAT': 5,
                                             'LRCX': 5,
                                             'KLAC': 5,
                                             'TER': 4,
                                             'ONTO': 4,
                                             'ACLS': 3,
                                             'AEIS': 3,
                                             'MKSI': 3,
                                             'ICHR': 3,
                                             'UCTT': 3,
                                             'FORM': 3,
                                             'CAMT': 4,
                                             'KLIC': 3,
                                             'ENTG': 4,
                                             'AMKR': 4,
                                             'CDNS': 5,
                                             'SNPS': 5}},
 'CLOUD_HYPERSCALERS': {'basket': ['MSFT',
                                   'AMZN',
                                   'GOOG',
                                   'META',
                                   'ORCL',
                                   'IBM',
                                   'BABA',
                                   'CRWV',
                                   'NBIS'],
                        'ai_exposure_score': {'MSFT': 5,
                                              'AMZN': 5,
                                              'GOOG': 5,
                                              'META': 4,
                                              'ORCL': 4,
                                              'IBM': 3,
                                              'BABA': 3,
                                              'CRWV': 5,
                                              'NBIS': 5}},
 'DATA_AI_INFRASTRUCTURE': {'basket': ['SNOW',
                                       'DDOG',
                                       'MDB',
                                       'NET',
                                       'AKAM',
                                       'DOCN',
                                       'ESTC',
                                       'TWLO',
                                       'NTNX',
                                       'GTLB',
                                       'VRSK'],
                            'ai_exposure_score': {'SNOW': 5,
                                                  'DDOG': 4,
                                                  'MDB': 5,
                                                  'NET': 4,
                                                  'AKAM': 3,
                                                  'DOCN': 3,
                                                  'ESTC': 5,
                                                  'TWLO': 3,
                                                  'NTNX': 4,
                                                  'GTLB': 5,
                                                  'VRSK': 4}},
 'DATA_CENTER_INFRASTRUCTURE': {'basket': ['VRT',
                                           'EQIX',
                                           'DLR',
                                           'ANET',
                                           'CSCO',
                                           'HPE',
                                           'DELL',
                                           'SMCI',
                                           'P',
                                           'CIEN',
                                           'APLD',
                                           'IREN',
                                           'CORZ',
                                           'COHR',
                                           'MOD',
                                           'NVT',
                                           'LITE'],
                                'ai_exposure_score': {'VRT': 5,
                                                      'EQIX': 5,
                                                      'DLR': 5,
                                                      'ANET': 5,
                                                      'CSCO': 3,
                                                      'HPE': 4,
                                                      'DELL': 4,
                                                      'SMCI': 5,
                                                      'P': 4,
                                                      'CIEN': 4,
                                                      'APLD': 4,
                                                      'IREN': 4,
                                                      'CORZ': 4,
                                                      'COHR': 4,
                                                      'MOD': 4,
                                                      'NVT': 4,
                                                      'LITE': 4}},
 'POWER_GRID': {'basket': ['CEG',
                           'VST',
                           'TLN',
                           'NEE',
                           'DUK',
                           'SO',
                           'AEP',
                           'ETR',
                           'PWR',
                           'ETN',
                           'GEV',
                           'NRG',
                           'GNRC',
                           'EME',
                           'HUBB',
                           'POWL',
                           'BEPC',
                           'FLNC'],
                'ai_exposure_score': {'CEG': 5,
                                      'VST': 5,
                                      'TLN': 4,
                                      'NEE': 3,
                                      'DUK': 3,
                                      'SO': 3,
                                      'AEP': 3,
                                      'ETR': 4,
                                      'PWR': 5,
                                      'ETN': 5,
                                      'GEV': 5,
                                      'NRG': 3,
                                      'GNRC': 3,
                                      'EME': 4,
                                      'HUBB': 4,
                                      'POWL': 5,
                                      'BEPC': 3,
                                      'FLNC': 4}},
 'ENTERPRISE_AI_SOFTWARE': {'basket': ['CRM',
                                       'NOW',
                                       'ADBE',
                                       'SAP',
                                       'TEAM',
                                       'HUBS',
                                       'ADSK',
                                       'WDAY',
                                       'INTU',
                                       'PATH',
                                       'AI',
                                       'SOUN',
                                       'GWRE',
                                       'CCC'],
                            'ai_exposure_score': {'CRM': 4,
                                                  'NOW': 5,
                                                  'ADBE': 4,
                                                  'SAP': 3,
                                                  'TEAM': 3,
                                                  'HUBS': 3,
                                                  'ADSK': 3,
                                                  'WDAY': 3,
                                                  'INTU': 4,
                                                  'PATH': 4,
                                                  'AI': 5,
                                                  'SOUN': 5,
                                                  'GWRE': 5,
                                                  'CCC': 5}},
 'CYBERSECURITY_AI_TRUST': {'basket': ['CRWD',
                                       'PANW',
                                       'ZS',
                                       'FTNT',
                                       'OKTA',
                                       'S',
                                       'TENB',
                                       'RPD',
                                       'QLYS',
                                       'VRNS',
                                       'CHKP',
                                       'SAIL',
                                       'RDWR',
                                       'RBRK'],
                            'ai_exposure_score': {'CRWD': 5,
                                                  'PANW': 5,
                                                  'ZS': 5,
                                                  'FTNT': 4,
                                                  'OKTA': 4,
                                                  'S': 4,
                                                  'TENB': 3,
                                                  'RPD': 3,
                                                  'QLYS': 3,
                                                  'VRNS': 3,
                                                  'CHKP': 3,
                                                  'SAIL': 4,
                                                  'RDWR': 2,
                                                  'RBRK': 4}},
 'INDUSTRIAL_AUTOMATION': {'basket': ['ROK',
                                      'ABBNY',
                                      'FANUY',
                                      'OMRNY',
                                      'CGNX',
                                      'ZBRA',
                                      'HON',
                                      'EMR',
                                      'PH',
                                      'ATS',
                                      'RRX'],
                           'ai_exposure_score': {'ROK': 5,
                                                 'ABBNY': 5,
                                                 'FANUY': 5,
                                                 'OMRNY': 5,
                                                 'CGNX': 4,
                                                 'ZBRA': 3,
                                                 'HON': 4,
                                                 'EMR': 5,
                                                 'PH': 4,
                                                 'ATS': 4,
                                                 'RRX': 3}},
 'ROBOTICS': {'basket': ['DE', 'HSAI', 'SERV', 'RR', 'ISRG', 'TSLA', 'MBLY', 'OUST', 'SYM'],
              'ai_exposure_score': {'DE': 4,
                                    'HSAI': 4,
                                    'SERV': 5,
                                    'RR': 5,
                                    'ISRG': 5,
                                    'TSLA': 5,
                                    'MBLY': 5,
                                    'OUST': 5,
                                    'SYM': 5}},
 'DEFENSE_NATIONAL_SECURITY': {'basket': ['PLTR',
                                          'LMT',
                                          'RTX',
                                          'NOC',
                                          'GD',
                                          'BA',
                                          'LDOS',
                                          'CACI',
                                          'HII',
                                          'MRCY',
                                          'BWXT',
                                          'RCAT',
                                          'LHX',
                                          'SAIC',
                                          'TDY',
                                          'AVAV',
                                          'KTOS'],
                               'ai_exposure_score': {'PLTR': 5,
                                                     'LMT': 4,
                                                     'RTX': 4,
                                                     'NOC': 4,
                                                     'GD': 3,
                                                     'BA': 3,
                                                     'LDOS': 4,
                                                     'CACI': 4,
                                                     'HII': 2,
                                                     'MRCY': 4,
                                                     'BWXT': 3,
                                                     'RCAT': 5,
                                                     'LHX': 4,
                                                     'SAIC': 3,
                                                     'TDY': 3,
                                                     'AVAV': 5,
                                                     'KTOS': 5}},
 'CONSUMER_AI': {'basket': ['AAPL',
                            'DUOL',
                            'SPOT',
                            'SNAP',
                            'PINS',
                            'RDDT',
                            'RBLX',
                            'NFLX',
                            'ROKU',
                            'APP',
                            'SHOP',
                            'ABNB'],
                 'ai_exposure_score': {'AAPL': 4,
                                       'DUOL': 5,
                                       'SPOT': 3,
                                       'SNAP': 4,
                                       'PINS': 4,
                                       'RDDT': 4,
                                       'RBLX': 5,
                                       'NFLX': 4,
                                       'ROKU': 4,
                                       'APP': 4,
                                       'SHOP': 4,
                                       'ABNB': 4}},
 'HEALTHCARE_LIFE_SCIENCES_AI': {'basket': ['TEM',
                                            'RXRX',
                                            'SDGR',
                                            'GH',
                                            'GEHC',
                                            'IQV',
                                            'VEEV',
                                            'BFLY',
                                            'CERT',
                                            'NTRA'],
                                 'ai_exposure_score': {'TEM': 5,
                                                       'RXRX': 5,
                                                       'SDGR': 5,
                                                       'GH': 4,
                                                       'GEHC': 4,
                                                       'IQV': 4,
                                                       'VEEV': 4,
                                                       'BFLY': 5,
                                                       'CERT': 4,
                                                       'NTRA': 4}},
 'TRANSPORTATION_LOGISTICS': {'basket': ['AUR',
                                         'UBER',
                                         'LYFT',
                                         'DASH',
                                         'UPS',
                                         'FDX',
                                         'GXO',
                                         'XPO',
                                         'CHRW',
                                         'JBHT',
                                         'UNP',
                                         'CSX'],
                              'ai_exposure_score': {'AUR': 5,
                                                    'UBER': 5,
                                                    'LYFT': 4,
                                                    'DASH': 4,
                                                    'UPS': 3,
                                                    'FDX': 3,
                                                    'GXO': 4,
                                                    'XPO': 3,
                                                    'CHRW': 3,
                                                    'JBHT': 3,
                                                    'UNP': 3,
                                                    'CSX': 3}},
 'INSURANCE_RISK': {'basket': ['PGR',
                               'ALL',
                               'CB',
                               'TRV',
                               'LMND',
                               'ROOT',
                               'UNH',
                               'ELV',
                               'CI',
                               'HUM',
                               'OSCR',
                               'MET',
                               'PRU',
                               'AFL'],
                    'ai_exposure_score': {'PGR': 4,
                                          'ALL': 3,
                                          'CB': 3,
                                          'TRV': 3,
                                          'LMND': 5,
                                          'ROOT': 5,
                                          'UNH': 4,
                                          'ELV': 3,
                                          'CI': 3,
                                          'HUM': 3,
                                          'OSCR': 4,
                                          'MET': 3,
                                          'PRU': 3,
                                          'AFL': 3}}}

SECTOR_DISPLAY_NAMES = {'COMPUTE': 'Compute',
 'SEMICAP_EQUIPMENT': 'Semicap & EDA',
 'CLOUD_HYPERSCALERS': 'Cloud & Platforms',
 'DATA_AI_INFRASTRUCTURE': 'Data & AI Infrastructure',
 'DATA_CENTER_INFRASTRUCTURE': 'Data Center Infrastructure',
 'POWER_GRID': 'Power & Grid',
 'ENTERPRISE_AI_SOFTWARE': 'Enterprise AI Software',
 'CYBERSECURITY_AI_TRUST': 'Cybersecurity & AI Trust',
 'INDUSTRIAL_AUTOMATION': 'Industrial Automation',
 'ROBOTICS': 'Robotics & Autonomy',
 'DEFENSE_NATIONAL_SECURITY': 'Defense & National Security',
 'CONSUMER_AI': 'Consumer AI',
 'HEALTHCARE_LIFE_SCIENCES_AI': 'Healthcare & Life Sciences AI',
 'TRANSPORTATION_LOGISTICS': 'Transportation & Logistics',
 'INSURANCE_RISK': 'Insurance & Risk'}

TICKER_DESIGNATIONS = {'GWRE': ('insurance_enablement',),
 'VRSK': ('insurance_enablement',),
 'CCC': ('insurance_enablement',)}

def ticker_to_sector() -> dict[str, str]:
    """Return the canonical one-to-one ticker ownership map."""
    return {
        ticker: sector
        for sector, cfg in SECTOR_CONFIG.items()
        for ticker in cfg["basket"]
    }


def all_tickers() -> tuple[str, ...]:
    """Return all canonical tickers in deterministic sector order."""
    return tuple(
        ticker
        for cfg in SECTOR_CONFIG.values()
        for ticker in cfg["basket"]
    )


def validate_sector_config() -> dict[str, int]:
    """Fail fast when the configured universe violates an accepted contract."""
    if len(SECTOR_CONFIG) != EXPECTED_SECTOR_COUNT:
        raise ValueError(
            f"Expected {EXPECTED_SECTOR_COUNT} sectors; found {len(SECTOR_CONFIG)}"
        )

    seen: dict[str, str] = {}
    duplicates: dict[str, list[str]] = {}
    for sector, cfg in SECTOR_CONFIG.items():
        basket = [str(ticker).upper().strip() for ticker in cfg.get("basket", [])]
        scores = cfg.get("ai_exposure_score", {})
        if len(basket) != len(set(basket)):
            raise ValueError(f"Duplicate ticker inside {sector}")
        if set(scores) != set(basket):
            missing = sorted(set(basket) - set(scores))
            extra = sorted(set(scores) - set(basket))
            raise ValueError(
                f"Exposure-score mismatch in {sector}: missing={missing}, extra={extra}"
            )
        invalid_scores = {
            ticker: score
            for ticker, score in scores.items()
            if not isinstance(score, int) or not 1 <= score <= 5
        }
        if invalid_scores:
            raise ValueError(f"Invalid exposure scores in {sector}: {invalid_scores}")
        for ticker in basket:
            if ticker in seen:
                duplicates.setdefault(ticker, [seen[ticker]]).append(sector)
            else:
                seen[ticker] = sector

    if duplicates:
        raise ValueError(f"Tickers assigned to multiple sectors: {duplicates}")
    if len(seen) != EXPECTED_TICKER_COUNT:
        raise ValueError(
            f"Expected {EXPECTED_TICKER_COUNT} unique tickers; found {len(seen)}"
        )
    unknown_designations = sorted(set(TICKER_DESIGNATIONS) - set(seen))
    if unknown_designations:
        raise ValueError(f"Designations reference unknown tickers: {unknown_designations}")
    return {"sectors": len(SECTOR_CONFIG), "tickers": len(seen)}


UNIVERSE_COUNTS = validate_sector_config()
